config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  #### User Resources ####
  get '/signup',                           to: 'users#new', as: 'new_user'
  get '/profile',                          to: 'users#show'
  resources :users,                        only: [:index, :create]


  #### Session Resources ####
  get '/login',                            to: 'sessions#new', as: :new_session
  resources :sessions,                     only: [:create, :destroy]


  #### Oauth Singn up routes ####
  get '/auth/facebook',                    as: :facebook_login
  get '/auth/facebook/callback',           to: 'sessions#create'


  #### Search Resources ####
  get "/search",                           to: 'search#index', as: 'search'


  #### Recipe Resources ####
  resources :recipes,                      only: [:new, :create, :show, :update, :index]
  namespace :recipes                       do
    get "/:id/search",                     to: 'search#index', as: 'ingredients_search'
  end

  #### Meal Resources ####
  resources :meals,                        only: [:new, :create, :show, :update, :index]
  namespace :meals                         do
    get "/:id/search",                     to: 'search#index', as: 'ingredients_search'
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, :description, presence: true

  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :meals, through: :meal_recipes
end

app/controllers/recipes/search_controller.rb
class Recipes::SearchController < ApplicationController

  def index
    @item = params[:q]
    @food_items = Food.find_by_title(params[:q])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipes_path, sucess: "You have successfully created a recipe! Let's get started on adding some ingredients!"
    else
      redirect_to new_recipe_path, danger: "Missing information for your recipe please try again."
    end
  end

  def show
    @recipe = found_recipe
  end

  def update
    if params.include?(:food_name)
      update_ingredients
    else
      update_recipe_information
    end
  end

  def index
    @recipes = current_user.recipes
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :directions)
  end

  def found_recipe
    Recipe.find(params[:id])
  end

  def update_recipe
    redirect_to recipe_path(@recipe.id),
    success: "You successfully updated #{@recipe.name}!"
  end

  def fail_to_update
    redirect_to recipe_path(@recipe.slug),
    danger: "Failed to update #{@recipe.name}!"
  end

  def update_recipe_information
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    if @recipe.save
      update_recipe
    else
      fail_to_update
    end
  end

  def update_ingredients
    @ingredient              = Ingredient.find_or_create_by(name: params[:food_name])
    @ingredient.brand        = params[:food_brand]
    @ingredient.calories     = params[:food_calories]
    @ingredient.fat          = params[:food_fat]
    @ingredient.serving_size = params[:food_serving]
    if @ingredient.save
      params[:ingredients] = @ingredient
      update_recipe_ingredients
    else
      fail_to_update
    end
  end

  def update_recipe_ingredients
    @recipe = Recipe.find(params[:id])
    @recipe.ingredients << params[:ingredients]
    if @recipe.save
      update_recipe
    else
      fail_to_update
    end
  end
end

app/views/recipes/index.html.erb
<div class="container" >
  <h1 style="position: relative; left: 30%;"> Welcome to your Recipe Box </h1>
  <% if !recipes? %>
  <div class="recipe-card">
    <% current_user.recipes.each do |recipe| %>
    <div class="card-block" style="position: relative; left: 25%;">
      <h5>Recipe Name: <strong><%= recipe.name %></strong></h5>
      <h5> Recipe Description: <strong><%= recipe.description %></strong></h5>
      <%= button_to "View Recipe", recipe_path(recipe.id), class: "btn btn-primary", method: "get" %>
    </div><br>
    <% end %>
  </div>
  <% else %>
  <p style="position: relative; left: 35%;"> You currently have no new recipes </p>
  <% end %>
  <h5 style="position: relative; left: 36%;"> Want to create a new recipe? Click Below and get started!</h5>
  <div class ="create-recipe" style="position: relative; left: 44.5%;">
  <%= button_to "Create a Recipe", new_recipe_path, class: "btn btn-primary", method: "get" %>
</div>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <div class="card col-md-offset-4">
    <div class="card-block">
      <%= form_for @recipe do |f| %>
      <div class="card-header">
        <h7> Please enter a name and a brief decscription to get started </h7><br><br>
      </div>
      <div class="form-group">
        <%= f.text_field :name, class:"form-control", placeholder: :name %>
      </div>
      <div class="form-group">
        <%= f.text_field :description, class:"form-control", placeholder: :description %>
      </div>
      <div class="form-group">
        <%= f.submit "Create Recipe!", class:'btn btn-success'  %>
        <% end %>
        <br><br>
      </div>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="card-block" style="position: relative; left: 25%;">
    <main class="recipe">
      <section>
        <h5> Recipe Name: <strong> <%= @recipe.name %> </strong></h5>
        <h5> Description: <strong> <%= @recipe.description %></strong></h5>
        <% if !has_ingredients?(@recipe) %>
        <table class="table table-hover table-condensed">
          <h5> Nutritional Information: </h5>
          <thead>
            <tr>
              <th> Ingredient Name </th>
              <th> Calories </th>
              <th> Fat </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <% @recipe.ingredients.each do |ingredient|%>
              <td> <%= ingredient.name %> </td>
              <td> <%= ingredient.calories %> </td>
              <td> <%= ingredient.fat %> </td>
            </tr>
            <% end %>
          </tbody>
          <% end %>
          <tfoot>
            <tr>
              <td> <strong> Total: </strong> </td>
              <td> <%= total_calories(@recipe) %> </td>
              <td> <%= total_fat(@recipe) %> </td>
            </tr>
          </tfoot>
        </table>
      </div><br>
      <%= form_tag recipes_ingredients_search_path, method: :get, class: "form-inline" do %>
      <div class="form-group search-field" style="position: relative; left: 38%;">
        <%= text_field_tag :q, "Search", class: "form-control", id: "Find Food" %>
        <%= submit_tag "search", class: "btn btn-primary", id: "search " %>
        <% end %> <br><br>
      </div>
      <h7 style="position: relative; left: 15%;"> ** For best results be as specific as you can in the type of food. For example specifiy the type of apple you want (Gala, Granny Smith, etc.) ** </h7>
    </div>
    <div class="container">
    <p> Preparation Instructions: </p>
    <%= form_for @recipe, url: recipe_path, method: "patch" do |f| %>
    <div class="form-group">
      <%=  f.text_area :directions, class: "form-control", placeholder: recipe_directions(@recipe) %>
      <%= hidden_field_tag :recipe_id, @recipe.id %>
    </div>
    <%= button_to "Update Directions", recipe_path, class: 'btn btn-success', method: "patch" %>
  </div>
  <% end %>
</div>
</section>
</main>
</div>
</div>