config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  #### User Resources ####
  get '/signup',                           to: 'users#new', as: 'new_user'
  get '/profile',                          to: 'users#show'
  resources :users,                        only: [:index, :create]


  #### Session Resources ####
  get '/login',                            to: 'sessions#new', as: :new_session
  resources :sessions,                     only: [:create, :destroy]


  #### Oauth Singn up routes ####
  get '/auth/facebook',                    as: :facebook_login
  get '/auth/facebook/callback',           to: 'sessions#create'


  #### Search Resources ####
  get "/search",                           to: 'search#index', as: 'search'


  #### Recipe Resources ####
  resources :recipes,                      only: [:new, :create, :show, :update, :index]
  namespace :recipes                       do
    get "/:id/search",                     to: 'search#index', as: 'ingredients_search'
  end

  #### Meal Resources ####
  resources :meals,                        only: [:new, :create, :show, :update, :index]
  namespace :meals                         do
    get "/:id/search",                     to: 'search#index', as: 'ingredients_search'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password validations: false, if: :social_login?

  validates :name, :email, presence: true
  validates :email, uniqueness: true
  validates :password, confirmation: true

  has_many :recipes
  has_many :meals 

  def find_or_create_by_omniauth(user_data)
    user = User.find_or_create_by(uid: user_data[:uid])
    user.update(user_information(user_data))
    user
  end

  def user_information(user_data)
    user_info = user_data[:info]
    {name: user_info[:name], email: user_info[:email], avatar: user_info[:image], token: user_data[:token], social_login: true}
  end

  def social_login?
    self.social_login.eql?(true)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to profile_path, success: "You have successfully signed up! Welcome to The Count!"
    else
      redirect_to new_user_path, danger: "Failed to create an account, please try again."
    end
  end

  def show
    @user = found_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def found_user
    User.find(session[:user_id])
  end
end

app/views/users/new.html.erb
<div class="container">
  <div class="card col-md-offset-4">
    <div class="card-block">
      <%= form_for @user do |f| %>
      <div class="card-header">
        <h6>Have an account? <%= link_to 'Log in' %> </h6>
      </div>
      <div class="form-group">
        <%= f.text_field :name, class:"form-control", placeholder: :name %>
      </div>
      <div class="form-group">
        <%= f.text_field :email, class:"form-control", placeholder: :email %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, class:"form-control", placeholder: :password %>
      </div>
      <div class="form-group">
        <%= f.password_field :password_confirmation, class:"form-control", placeholder: "Re-enter password" %>
      </div>
      <div class="form-group">
        <%= f.submit "Sign me up!", class:'btn btn-success'  %>
        <% end %>
        <h5> Or </h5>
        <%= button_to "Log in with Facebook", facebook_login_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<header class="welcome-banner">
  <br><br><br><br>
  <div class="headline">
      <h3> Welcome to The Count, <%=@user.name %>! </h3>
      <%= button_to "View Your Recipes", recipes_path, class: "btn btn-primary", method: "get" %>
  </div>
</header>