config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  #### User Resources ####
  get '/signup',                           to: 'users#new', as: 'new_user'
  get '/profile',                          to: 'users#show'
  resources :users,                        only: [:index, :create]


  #### Session Resources ####
  get '/login',                            to: 'sessions#new', as: :new_session
  resources :sessions,                     only: [:create, :destroy]


  #### Oauth Singn up routes ####
  get '/auth/facebook',                    as: :facebook_login
  get '/auth/facebook/callback',           to: 'sessions#create'


  #### Search Resources ####
  get "/search",                           to: 'search#index', as: 'search'


  #### Recipe Resources ####
  resources :recipes,                      only: [:new, :create, :show, :update, :index]
  namespace :recipes                       do
    get "/:id/search",                     to: 'search#index', as: 'ingredients_search'
  end

  #### Meal Resources ####
  resources :meals,                        only: [:new, :create, :show, :update, :index]
  namespace :meals                         do
    get "/:id/search",                     to: 'search#index', as: 'ingredients_search'
  end
end

app/views/shared/_flash.html.erb
<article>
  <% flash.each do |key, value| %>
    <%= content_tag :div, sanitize(value), class: "alert alert-#{key}" %>
  <% end %>
</article>

app/views/shared/_food.html.erb
<div class="container">
<table class="table table-hover table-condensed">
   <h2>Possible Matches for "<%= @item %>" </h2>
  	<thead>
  		<tr>
        <th> Name</th>
        <th> Brand </th>
        <th> Calories </th>
        <th> Fat </th>
        <th> Serving Size</th>
  		</tr>
  	</thead>
  	<tbody>
      <tr>
      <% @food_items.each do |food_item| %>
  		<td> <%= food_item.name %> </td>
  		<td> <%= food_item.brand %> </td>
  		<td> <%= food_item.calories %> </td>
  		<td> <%= food_item.fat %> </td>
  		<td> <%= food_item.serving_size %> </td>
   </tr>
      <% end %>
   </tbody>
</table>
</div>

app/views/shared/_navbar.html.erb
<nav id="nav" class="navbar navbar-default" role="navigation">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
</div>
<div class="collapse navbar-collapse" id="navbar-collapse-1">
  <ul class="nav navbar-nav">
    <% if logged_in? %>
    <div class="list-inline pull-left" id="user-left">
      <li class="list-group-item"><%= link_to "Home", root_path %></li>
      <li class="list-group-item"><%= link_to "Profile", profile_path %></li>
      <li class="list-group-item"><%= link_to "Recipe Box", recipes_path  %></li>
      <li class="list-group-item"><%= link_to "Your Meals", meals_path  %></li>
    </div>
    <div class="list-inline pull-right" id="user-right">
      <% if missing_avatar? %>
        <li class="list-group-item"><%= image_tag("missing_user_avatar.png", class: "img-circle") %>
      <% else %>
        <li class="list-group-item"><%= image_tag(current_user.avatar, class: "img-circle") %>
      <% end %>
    <li class="list-group-item"><%= link_to "Logout", session_path(current_user), method: 'delete' %></li>
  </div>
    <% else %>
    <div class="list-inline pull-left" id="guest-left">
      <li class="list-group-item"><%= link_to "Home", root_path %></li>
      </div>
      <div class="list-inline pull-right" id="guest-right">
        <li class="list-group-item"><%= link_to "Log in", new_session_path %></li>
        <li class="list-group-item"><%= link_to "Sign Up", new_user_path %></li>
      <% end %>
    </ul>
</div>
</nav>